### ISSUE TITLE
continuousWorld settings not working

### ISSUE THREAD

**Issue by CleberDSantos** [aebadirad/Leaflet.AutoLayers#5] opened 2016-11-14 15:28 UTC
At leaflet-autolayers.js line 382, i was needed change follow code :

  `continuousWorld: mapConfig.continuousWorld ? mapConfig.continuousWorld : true,`

to:
`continuousWorld: mapConfig.continuousWorld != undefined ? mapConfig.continuousWorld : true,`
 

Data input example:
`{   
   "continuousWorld":false,
   "selectedBasemap":"World_Street_Map",
   "mapServers":[
      {  
         "url":"http://services.arcgisonline.com/arcgis/rest/services",
         "dictionary":"http://services.arcgisonline.com/arcgis/rest/services?f=pjson",
         "tileUrl":"/MapServer/tile/{z}/{y}/{x}",
         "name":"ArcGIS Online",
         "type":"esri",
         "baseLayers":[
            "World_Street_Map"
         ]
      }
   ]}`

**Comment by aebadirad** [comment] 2016-11-18 21:02
I've updated and addressed continuous world, it should function as intended now.

**Comment by aebadirad** [comment] 2017-01-02 22:59
Assuming the fix to this worked and will close the issue, please open a new one if there's anything else that needs to be done.

**Closed as completed by aebadirad** 2017-01-02 22:59 UTC
